### ISSUE TITLE
Optional volumes

### ISSUE THREAD

**Issue by dmiric** [mrsimonemms/devpod-provider-hetzner#18]
## Is your feature request related to a problem? Please describe
Can we have volumes be optional? Right now when I create a server it also makes an additional volume for storage. Most of the time projects can easily fit on machine with 40 GB of disk space.

**Comment by mrsimonemms** [comment]
Not sure. How would this work from an implementation point of view? I don't believe DevPod has a flag for this and I don't think you'd want it as an envvar.

Also, putting things on the machine could cause data loss - if your machine is stopped/terminated with the data in the ephemeral volume then you've lost it.

This feels like it might be like when we all stick data in a container "because I'll never restart it" and then we do and lose it.

**Comment by dmiric** [comment]
Yeah it's good as it is I think. I would like to move my database there too
now I'm just not 100% sure how to find volume path. I'm pretty new to this
docker setup stuff so not 100% sure where to look for a volume path.
